### ISSUE TITLE
Why require PHP 7.4?

### ISSUE THREAD

**Issue by danepowell** [loophp/phposinfo#1]
This commit broke compatibility between phposinfo and platforms running PHP 7.3: https://github.com/loophp/phposinfo/commit/0526c49dbf963233b76020884dabec4a53dec8f7

PHP 7.3 is still [officially supported until December 2021](https://www.php.net/supported-versions.php), and still widely used. Is there a particular reason you removed support? Can we get it back? Our downstream project (https://github.com/acquia/blt) still needs to support PHP 7.3 users.

**Comment by drupol** [comment]
Hi Dane,

I will restore it, sorry about that.

**Comment by drupol** [comment]
Fixed! https://github.com/loophp/phposinfo/releases/tag/1.7.1

**Comment by danepowell** [comment]
Thanks for the quick response!
